version: '3.8'

services:
  db:
    container_name: jspay-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DATABASE: ${DATABASE_NAME}
    ports:
      - "5432:5432"

  app:
    container_name: jspay-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db