version: '3.8'

services:
  db:
    container_name: jspay-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app:
    container_name: jspay-app
    build:
      context: docker/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db